- hosts: appservers
  become: yes
  gather_facts: no
  vars:
    users:
      - jaime
      - sansa
      - robert
  tasks:
    - name: update apt-get
      apt:
        upgrade: dist
        force_apt_get: yes
      tags: apt
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      tags: [ci,git]
    - name: intall make
      ansible.builtin.apt:
        name: make
        state: present
        update_cache: yes
      tags: [ci,make]
    - name: install nodejs
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: yes
      tags: [ci,nodejs]
    - name: create users
      ansible.builtin.user:
        name: "{{ item }}"
      loop: "{{users}}"
      become: yes
