- hosts: appservers
  become: yes
  gather_facts: no
  vars:
    users:
      - {name: jaime, email: jaime@mail.com}
      - {name: sansa, email: sansa@mail.com}
      - {name: robert, email: robert@mail.com}
  tasks:
    - name: create users
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        append: yes
        create_home: yes
      loop: "{{users}}"
    - name: add configs for users
      ansible.builtin.template:
        src: files/.gitconfig.j2
        dest: "/home/{{item.name}}/.gitconfig"
        owner: "{{item.name}}"
        group: "{{item.name}}"
      loop: "{{users}}"
    # - name: create .ssh each users
    #   ansible.builtin.file:
    #     path: "/home/{{item.name}}/.ssh"
    #     owner: "{{item.name}}"
    #     group: "{{item.name}}"
    #     state: directory
    #     mode: "0644"
    #   loop: "{{users}}"
    - name: create auth keys each users
      authorized_key:
        user: "{{item.name}}"
        key: "{{lookup('file', 'files/my_key.pub')}}"
        state: present
      loop: "{{users}}"