- hosts: appservers
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: update nginx html
      ansible.builtin.copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
      notify:
      - restart nginx
    - name: update nginx conf
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
      - restart nginx
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx 
        state: reloaded
        