- hosts: all
  become: yes
  gather_facts: yes
  vars: 
    user: {name: test, email: test@example.com}
    str: "This is server {{ansible_hostname}}!"
    date: "{{ansible_date_time}}"
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{user.name}}"
        create_home: yes
        append: yes
        state: present
    - name: install git
      ansible.builtin.package:
        name: git
        state: present
    - name: install cowsay
      ansible.builtin.package:
        name: cowsay
        state: present
        update_cache: yes
    #   when: ansible_distribution == 'Ubuntu'
    # - name: install EPEL repository on CentOS
    #   ansible.builtin.yum:
    #     name: epel-release
    #     state: present
    #     update_cache: yes
    #   when: ansible_distribution == 'CentOS'
    # - name: install cowsay CentOS
    #   ansible.builtin.yum:
    #     name: cowsay
    #     update_cache: yes
    #     state: present
    #   when: ansible_distribution == 'CentOS'
    - name: cowsay
      ansible.builtin.shell: "cowsay 'This is server {{ansible_hostname}}!'"
      register: cow
    - name: create gitconfig for user
      ansible.builtin.template:
        src: templates/.gitconfig.j2
        dest: "/home/{{user.name}}/.gitconfig"
        owner: "{{user.name}}"
        group: "{{user.name}}"
    - name: create html file
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "/home/{{user.name}}/index.html"
        owner: "{{user.name}}"
        group: "{{user.name}}"
